const data = [
  {
    name: 'Buzo Rip Curl Guard',
    description: 'Buzo Rip Curl Crew Guard. Frisa pesada. Regular fit. Manga básica. Tira tejido retro. Parche logo. Multietiquetas. 88% Algodón 12% Poliester.',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 10999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21402foto95323th.jpg',
    category: 'Buzo',
    brand: 'Rip Curl',
    disabled: false,
  },
  {
    name: 'Remera DC Bandana',
    description: 'Remera manga corta DC Bandana. Full print. Jersey 30/1. Regular fit. Avios DC. 100% algodón.',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 9699,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21406foto95347th.jpg',
    category: 'Remera',
    brand: 'DC',
    disabled: false,
  },
  {
    name: 'Remera Rip Curl Pro',
    description: 'Remera Rip Curl Pro. Estampa en espalda, frente y mangas. Standard fit. 100% algodón.',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 4999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21405foto95345.jpg',
    category: 'Remera',
    brand: 'Rip Curl',
    disabled: false,
  },
  {
    name: 'Buzo Rip Curl Pro',
    description: 'Buzo Rip Curl Pro. Rústico. Estampa en espalda, frente y brazos. Bolsillo canguro. Capucha con tiras de ajuste. 100% algodón',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 13999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21404foto95342.jpg',
    category: 'Buzo',
    brand: 'Rip Curl',
    disabled: false,
  },

  {
    name: 'Remera Zoo York Immergruen',
    description: ' Remera Zoo York Immergruen. Jersey 100% algodón. Over size fit. Estampa logo.',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 3999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21385foto95276.jpg',
    category: 'Remera',
    brand: 'Zoo York',
    disabled: false,
  },
  {
    name: 'Pantalon Circa Chino',
    description: 'Pantalon Circa Chino de gabardina, tiro medio, bolsillos laterales y traseros invisibles',
    stock: 1589,
    stock_by_size: [{ size: '30', stock: 1589 }, { size: '32', stock: 1589 }, { size: '34', stock: 1589 }, { size: '36', stock: 1589 }, { size: '38', stock: 1589 }],
    price: 9699,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21339foto95127.jpg',
    category: 'Pantalon',
    brand: 'Circa',
    disabled: false,
  },
  {
    name: 'Pantalon Rusty Cargo X-Charge',
    description: ' Pantalon Rusty Cargo X-Charge. De gabardina de algodón 100%. Calce recto relajado con bolsillos cargo en laterales. Bolsillos traseros ojal con grifa de marca. Confección al tono. Lavado enzimático en prenda. ',
    stock: 1589,
    stock_by_size: [{ size: '30', stock: 1589 }, { size: '32', stock: 1589 }, { size: '34', stock: 1589 }, { size: '36', stock: 1589 }, { size: '38', stock: 1589 }],
    price: 10999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21362foto95160.jpg',
    category: 'Pantalon',
    brand: 'Rusty',
    disabled: false,
  },
  {
    name: 'Campera Y Tú Quique? Puffer Cord',
    description: 'Campera Y Tú Quique? Puffer poli. Con capucha y cordón de ajuste. Interior y capucha forrados en corderito. Bolsillos laterales. ',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 19999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21312foto95044.jpg',
    category: 'Campera',
    brand: 'Y Tú Quique?',
    disabled: false,
  },
  {
    name: 'Campera Y Tú Quique? Puffer Cord',
    description: '',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 19999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21308foto95031.jpg',
    category: 'Campera',
    brand: 'Y Tú Quique?',
    disabled: false,
  },
  {
    name: 'Pantalon Adidas Pintuck',
    description: 'Pantalon Adidas Pintuck. Corte holgado. Tejido de lona ligera. Bolsillos laterales con cierre. Detalles de pequeños frunces. ',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 13999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21149foto94563.jpg',
    category: 'Pantalon',
    brand: 'Adidas',
    disabled: false,
  },
  {
    name: 'Rompeviento Adidas Coach',
    description: 'Rompeviento Adidas Coach. Cierre de cremallera de doble sentido. Tejido plano. Material taslan. Bolsillos frontales dobles. ',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 13999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21148foto94560.jpg',
    category: 'Campera',
    brand: 'Adidas',
    disabled: false,
  },
  {
    name: 'Buzo Adidas Shmoo',
    description: 'Buzo Adidas Shmoo. Corte clásico. Capucha con cordón de ajuste. Felpa francesa 100 % algodón. Bolsillo canguro. Puños y dobladillo acanalados. ',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 17999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item17985foto94550.jpg',
    category: 'Buzo',
    brand: 'Adidas',
    disabled: false,
  },
  {
    name: 'Chaleco Rip Curl Puffer',
    description: 'Chaleco Rip Curl Puffer. Poliester repelente al agua. Chaleco puffer con capucha. Canelones de 12cm de ancho. Cierre diente de perro. Multietiquetas. 100% poliester.',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 14999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21390foto95285.jpg',
    category: 'Chaleco',
    brand: 'Rip Curl',
    disabled: false,
  },
  {
    name: 'Campera Rip Curl Puffer',
    description: 'Campera Rip Curl Puffer. Poliester repelente al agua. Campera corta puffer con capucha. Canelones de 12cm. Cierre diente de perro. Cordón con detalle de PU. Multietiquetas. 100% poliéster.',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 9699,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21397foto95329.jpg',
    category: 'Campera',
    brand: 'Rip Curl',
    disabled: false,
  },
  {
    name: 'Campera Rip Curl Puffer',
    description: 'Campera Rip Curl Puffer. Poliester repelente al agua. Campera corta puffer con capucha. Canelones de 12cm. Cierre diente de perro. Cordón con detalle de PU. Multietiquetas. 100% poliéster.',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 24999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21396foto95310.jpg',
    category: 'Campera',
    brand: 'Rip Curl',
    disabled: false,
  },
  {
    name: 'Campera Volcom Hernan',
    description: 'Campera Volcom Hernan con capucha acordonada, cierre metálico. Microcanvas DWR \n  Interior con matelasé \n Puños de ribb \n Bordado Volcom StoneRegular fit',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 24999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21373foto95179.jpg',
    category: 'Campera',
    brand: 'Volcom',
    disabled: false,
  },
  {
    name: 'Buzo Rip Curl Classic Po',
    description: ' Buzo Rip Curl Classic Po  con capucha, confeccionada en felpa de algodón 100%, cuenta con un bolsillo delantero  canguro y gráficos del inconfundible logotipo de la marca en la parte delantera.',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 11600,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21375foto95183.jpg',
    category: 'Buzo',
    brand: 'Rip Curl',
    disabled: false,
  },
  {
    name: 'Buzo Rusty Cheater',
    description: ' Canguro Básico Frisa invisible de algodón con poliester en la malla interna.Capucha forrada en jersey al tono. Ojalillos metalicos grabados, cordón redondo de algodón con punteras metálicas. Puños y cintura de rib complemento con lycra. Logo en el frente - Central en la espalda, ambos en Serigrafía Grifa de marca tejida en el lateral  Etiqueta de marca y talle en cuello',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 9399,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21376foto95184.jpg',
    category: 'Buzo',
    brand: 'Rusty',
    disabled: false,
  },
  {
    name: 'Buzo Vans OTW Po II',
    description: 'Buzo Vans OTW Po II Tela: Algodón| Polyester| Lino| Viscosa  Composición: 85% poliéster - 15% poliéster \n  Color: Negro Fit Regular \n  Detalles Capucha - Estampa - Bolsillo canguro',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 12900,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21367foto95168.jpg',
    category: 'Buzo',
    brand: 'Vans',
    disabled: false,
  },
  {
    name: 'Buzo Vans Crew Classic',
    description: 'Buzo en frisa escote redondo. Estampa VANS en el frente. Etiqueta de marca y talle, grifa Vans y cinta interior personalizada.',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 9699,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21370foto95171.jpg',
    category: 'Buzo',
    brand: 'Vans',
    disabled: false,
  },
  {
    name: 'Remera Volcom Smile',
    description: ' Remera Volcom Smile manga corta, estampa en frente. Regular Fit. en Jersey 30/1',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 9699,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21334foto95108.jpg',
    category: 'Remera',
    brand: 'Volcom',
    disabled: false,
  },
  {
    name: 'Pantalon Rip Curl Slouchy Plain',
    description: 'Pantalon Rip Curl Slouchy Plain de Gabardina de alta densidad. Slouch fit \n Tiro alto \n Pinzas delanteras y traseras \n Lavado suavizado \n Multietiquetas \n 100% algodón',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 7999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21328foto95074.jpg',
    category: 'Pantalon',
    brand: 'Rip Curl',
    disabled: false,
  },
  {
    name: 'Campera Y Tú Quique? Puffer',
    description: '',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 16999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21327foto95066.jpg',
    category: 'Campera',
    brand: 'Y Tú Quique?',
    disabled: false,
  },
  {
    name: 'Buzo Volcom Hood Eagle',
    description: 'Buzo Volcom Hood Eagle.  Estampa en delantero. Bordado Volcom Stone en capucha. Etiqueta tejida en ruedo. Oversize fit. Frisa algoón. ',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 8999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item20795foto93337.jpg',
    category: 'Buzo',
    brand: 'Volcom',
    disabled: false,
  },
  {
    name: 'Campera Rip Curl Parka',
    description: 'Campera Rip Curl Parka. Gabardina algodón. Parka con capucha. Detalle de piel en borde. Cordón de ajuste en cintura. Bolsillos delanteros. Ruedo trasero con forma. Multietiquetas. 50% algodón 50% poliester.',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 9699,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item20631foto92434.jpg',
    category: 'Campera',
    brand: 'Rip Curl',
    disabled: false,
  },
  {
    name: 'Remera Rip Curl Heritage Loose',
    description: 'Remera manga larga combinadas, Rip Curl Heritage Loose, Estampa en delantero \n JERSEY 30/1 \n Sobremangas com mangas melange \n Grifa logo \n 100% Algodon',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 4999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21293foto94998.jpg',
    category: 'Remera',
    brand: 'Rip Curl',
    disabled: false,
  },
  {
    name: 'Buzo Volcom Liv Homax',
    description: 'Buzo Volcom Liv Homax. Manga ranglan combinada. Cordón al tono con puntera metálica y ojalillo metalico Volcom. Estampa en delantero. Etiqueta tejida lateral. Regular fit. Frisa.',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 11999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21208foto94742.jpg',
    category: 'Buzo',
    brand: 'Volcom',
    disabled: false,
  },

  {
    name: 'Jogging Deportivo Champion Graphic',
    description: 'Jogging Champion de frisa, regular fit. Cintura elastizada. Bolsillos laterales. Estampa en pierna.  50% Algodon 50% Poliester',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 9999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21026foto94138.jpg',
    category: 'Pantalon',
    brand: 'Champion',
    disabled: false,
  },

  {
    name: 'Remera Champion Deportivo',
    description: 'Remera Champion Classic Jersey de algodón hilado en anillos de 5.2 oz para una sensación más suave (los grises y los brezos son una mezcla rica en algodón). Construido con una densidad de puntada más alta para mayor durabilidad. Ajuste atlético a través de los hombros y el cuerpo con un dobladillo inferior más estrecho para un ajuste moderno. Cuello de canalé más estrecho y ajustado que optimiza tu look. Cinta de cuello suave a juego para no irritar. Resistente costura de doble aguja en mangas y dobladillo inferior. Logotipo serigrafiado en el centro del pecho, parche C en la manga. Cuerpo, cuello y puños de canalé 1x1 100% algodón.',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 5999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item21025foto94137.jpg',
    category: 'Remera',
    brand: 'Champion',
    disabled: false,
  },
  {
    name: 'Remera Zoo York Cracker',
    description: 'Remeron Zoo York Cracker. Jersey 100% Algodón.  Estampa logo. Unisex. ',
    stock: 1589,
    stock_by_size: [{ size: 'S', stock: 1589 }, { size: 'M', stock: 1589 }, { size: 'L', stock: 1589 }, { size: 'XL', stock: 1589 }, { size: 'XXL', stock: 1589 }],
    price: 3999,
    discount: 0,
    image: 'https://www.cristobalcolon.com/fullaccess/item20858foto93616.jpg',
    category: 'Remera',
    brand: 'Zoo York',
    disabled: false,
  },

];

module.exports = data;
